[debug]
logLevel = "info"
flushLevel = "trace"
profile = false

# ^ Profile reports timings of operations into gtsplugin.log
# Used to debug performance hit by specific functions
# Accepts only true/false. Making any typo in this setting will crash the game.

[frame]
initDelay = 0
step = 0

[voice]
# How deep the voice of NPC's can be if NPC size is > 1.0.
# Values below 1.0 won't have any effect. Change the value above 1.0 to apply effect.
# Default: 1.0 (always keep normal voice). Going above 2.0 is not recommended.
# Formula: 1.0 / maxVoiceFrequency. Value can't be bigger than 10.0

maxVoiceFrequency = 1.0

[tremor]
# linear, smoothstep, softcore, cubic
method = "linear"
# Contolls falloff this is the scale at which falloff=50%
halfScale = 0.91
# Controls the power at min/max scale
powerAtMin = 0.0
powerAtMax = 8.25
# Min/max scale points, this is just used for the powerAt dosen't min actual min/max
maxScale = 30.0
minScale = 0.0
