[SNDR] # Sound Descriptors ------------------------------------------------------------------------------------------------------------------------------------

lFootstep = "GTS.esp|1E93AB"
lJumpLand = "GTS.esp|183F43"

xlFootstep = "GTS.esp|271EF4"
xlRumble = "GTS.esp|36A06D"
xlSprint = "GTS.esp|319060"
xxlFootstep = "GTS.esp|16FB25"

growthSound = "GTS.esp|271EF6"
shrinkSound = "GTS.esp|364F6A"
GreybeardRumble = "GTS.esp|1CAD96"
MoanSound = "GTS.esp|09B0AC"
LaughSound_Type1 = "GTS.esp|09B0A9"
LaughSound_Type2 = "GTS.esp|5D3B5B"
BloodGushSound = "Skyrim.esm|10F78C"
VoreSound_Success = "Skyrim.esm|10FAE5"
VoreSound_Fail = "GTS.esp|851A37"
DefaultCrush = "GTS.esp|01102F"
Foot_SingleCrush_x8 = "GTS.esp|833433"
Foot_MultiCrush_x3_x8 = "GTS.esp|82E332"
GtsFallSound = "GTS.esp|183F43"
ClothTearSound = "GTS.esp|30EE54"
RumbleWalkSound = "GTS.esp|50423E"
GiantImpactSound = "Skyrim.esm|0C52F7"
VoreSwallow = "GTS.esp|56E747"
TriggerHG = "GTS.esp|578948"
ThighSandwichImpact = "GTS.esp|582B49"
HeavyStompSound = "GTS.esp|596F4E"
ShrinkToNothingSound = "GTS.esp|5BA659"
CrunchImpactSound = "GTS.esp|5D8C5C"
CrunchKillSound = "GTS.esp|5D8C5D"
BreastImpact = "GTS.esp|5E2E5F"
SoftHandAttack = "GTS.esp|5E2E60"
SwingImpact = "GTS.esp|68F0AD"

TinyCalamity_Impact = "GTS.esp|76DCD2"
TinyCalamity_Crush = "GTS.esp|76DCD3"
TinyCalamity_ReachedSpeed = "GTS.esp|7820D7"
TinyCalamity_AbsorbTiny = "GTS.esp|7B9BE6"
TinyCalamity_ReadyRune = "GTS.esp|7B9BE5"
TinyCalamity_SpawnRune = "GTS.esp|7B9BE4"
TinyCalamity_FingerSnap = "GTS.esp|8A7B4B"

Magic_ProtectTinies = "GTS.esp|772DD4"
Magic_BreakTinyProtection = "GTS.esp|777ED6"

ShrinkOutburstSound = "GTS.esp|6524A3"
TinyCalamitySound = "GTS.esp|65C6AA"

HighHeel_x2 = "GTS.esp|615875"
HighHeel_x4 = "GTS.esp|615877"
HighHeel_x8 = "GTS.esp|615878"
HighHeel_x12 = "GTS.esp|615879"
HighHeel_x24 = "GTS.esp|61587A"
HighHeel_x48 = "GTS.esp|61587B"
HighHeel_x96 = "GTS.esp|61587C"
HighHeel_Mega = "GTS.esp|61587D"

HighHeelLand_x2 = "GTS.esp|61588E"
HighHeelLand_x4 = "GTS.esp|61588F"
HighHeelLand_x8 = "GTS.esp|615890"
HighHeelLand_x12 = "GTS.esp|615891"
HighHeelLand_x24 = "GTS.esp|615892"
HighHeelLand_x48 = "GTS.esp|615893"
HighHeelLand_x96 = "GTS.esp|615894"
HighHeelLand_Mega = "GTS.esp|615895"

Normal_x2 = "GTS.esp|61587E"
Normal_x4 = "GTS.esp|61587F"
Normal_x8 = "GTS.esp|615880"
Normal_x12 = "GTS.esp|615881"
Normal_x24 = "GTS.esp|615882"
Normal_x48 = "GTS.esp|615883"
Normal_x96 = "GTS.esp|615884"
Normal_Mega = "GTS.esp|615885"

NormalLand_x2 = "GTS.esp|615886"
NormalLand_x4 = "GTS.esp|615887"
NormalLand_x8 = "GTS.esp|615888"
NormalLand_x12 = "GTS.esp|615889"
NormalLand_x24 = "GTS.esp|61588A"
NormalLand_x48 = "GTS.esp|61588B"
NormalLand_x96 = "GTS.esp|61588C"
NormalLand_Mega = "GTS.esp|61588D"

[MGEF] # Magic Effects ------------------------------------------------------------------------------------------------------------------------------------
TinyCalamity = "GTS.esp|1A2568"

# Explosive
GrowthSpurt1 = "GTS.esp|007928"
GrowthSpurt2 = "GTS.esp|1E42A5"
GrowthSpurt3 = "GTS.esp|1E42A6"

# Shrink
RestoreSize = "GTS.esp|005369"
RestoreSizeNPC = "GTS.esp|00536C"
ShrinkSpell = "GTS.esp|002850"
ShrinkAlly = "GTS.esp|0058D1"
ShrinkAllyAdept = "GTS.esp|452F17"
ShrinkAllyExpert = "GTS.esp|452F18"
ShrinkEnemy = "GTS.esp|00387B"
ShrinkEnemyAOE = "GTS.esp|0DCDC5"
ShrinkEnemyAOEMast = "GTS.esp|0DCDCA"
ShrinkBolt = "GTS.esp|3C5278"
ShrinkStorm = "GTS.esp|3C527C"

# Grow
SwordEnchant = "GTS.esp|00FA9E"
EnchGigantism = "GTS.esp|3EDAC5"
ShrinkToNothing = "GTS.esp|009979"
SlowGrowth = "GTS.esp|019C3D"
SlowGrowthDual = "GTS.esp|086C8D"
GrowthSpell = "GTS.esp|0022EB"
GrowthSpellAdept = "GTS.esp|45D124"
GrowthSpellExpert = "GTS.esp|45D125"
GrowAlly = "GTS.esp|0058D5"
GrowAllyAdept = "GTS.esp|452F15"
GrowAllyExpert = "GTS.esp|452F16"


# Absorb
AbsorbMGEF = "GTS.esp|00B470"
TrueAbsorb = "GTS.esp|22B0D5"

# Potions
EffectGrowthPotionWeak = "GTS.esp|3D4582"
EffectGrowthPotionNormal = "GTS.esp|7C8F02"
EffectGrowthPotionStrong = "GTS.esp|7C8F03"
EffectGrowthPotionExtreme = "GTS.esp|7C8F04"

EffectMightPotionWeak = "GTS.esp|7D8215"
EffectMightPotionNormal = "GTS.esp|7D8216"
EffectMightPotionStrong = "GTS.esp|7D8217"
EffectMightPotionExtreme = "GTS.esp|7D8218"

SizeMasteryPotionBasic = "GTS.esp|7CE013"

EffectEssencePotionWeak = "GTS.esp|7EC62B"
EffectEssencePotionNormal = "GTS.esp|7EC62C"
EffectEssencePotionStrong = "GTS.esp|7EC62D"
EffectEssencePotionExtreme = "GTS.esp|7EC62E"

ResistShrinkPotionWeak = "GTS.esp|3D4583"
ResistShrinkPotionNormal = "GTS.esp|7C8F09"
ResistShrinkPotionStrong = "GTS.esp|7C8F0A"
ResistShrinkPotionExtreme = "GTS.esp|7C8F0B"

EffectSizePotionWeak = "GTS.esp|3E38BB"
EffectSizePotionNormal = "GTS.esp|3E38BC"
EffectSizePotionStrong = "GTS.esp|3E38BD"
EffectSizePotionExtreme = "GTS.esp|3E38C0"

EffectSizeHungerPotion = "GTS.esp|42F7D6"
EffectSizeAmplifyPotion = "GTS.esp|452F1D"
SizeDrainPotion = "GTS.esp|5B5557"
ShrinkPoison = "GTS.esp|5B5552"

# Alchemy (scalable potions)
AlchEffectGrowth = "GTS.esp|89D948"
AlchEffectSize = "GTS.esp|89D94A"
AlchEffectEssence = "GTS.esp|89D947"
AlchEffectMight = "GTS.esp|89D946"
AlchResistShrink = "GTS.esp|89D949"

[SPEL] # Spells ------------------------------------------------------------------------------------------------------------------------------------

#---------- GTS
GtsVoreFearSpell = "GTS.esp|026D15"
SmallMassiveThreatSpell = "GTS.esp|1A2566"
ShrinkStorm = "GTS.esp|3C527A"
ShrinkBolt = "GTS.esp|3C5276"


#---------- Survival Mode
Survival_HungerStage0 = "ccQDRSSE001-SurvivalMode.esl|000876"
Survival_HungerStage1 = "ccQDRSSE001-SurvivalMode.esl|00087E"
Survival_HungerStage2 = "ccQDRSSE001-SurvivalMode.esl|000880"
Survival_HungerStage3 = "ccQDRSSE001-SurvivalMode.esl|000881"
Survival_HungerStage4 = "ccQDRSSE001-SurvivalMode.esl|000886"
Survival_HungerStage5 = "ccQDRSSE001-SurvivalMode.esl|000885"

[PERK] # Perks ------------------------------------------------------------------------------------------------------------------------------------

#---------- GTS
Acceleration = "GTS.esp|87F342"
AdditionalGrowth = "GTS.esp|151518"
BendLifeless = "GTS.esp|7913D9"
Breasts_Absorb = "GTS.esp|856B39"
Breasts_Intro = "GTS.esp|898845"
Breasts_Mastery = "GTS.esp|856B3B"
Breasts_Predominance = "GTS.esp|856B3D"
Breasts_Strangle = "GTS.esp|8ACC4C"
Breasts_Suffocate = "GTS.esp|856B3A"
Breasts_Vore = "GTS.esp|856B38"
ButtCrush_GrowingDisaster = "GTS.esp|5FC367"
ButtCrush_KillerBooty = "GTS.esp|5FC366"
ButtCrush_LoomingDoom = "GTS.esp|5FC369"
ButtCrush_NoEscape = "GTS.esp|5FC36A"
ButtCrush_UnstableGrowth = "GTS.esp|5FC368"
CalamityPerk = "GTS.esp|18E161"
ColossalGrowth = "GTS.esp|128CF7"
Cruelty = "GTS.esp|128CF8"
DarkArts = "GTS.esp|64319B"
DarkArts_Aug = "GTS.esp|64319C"
DarkArts_Aug2 = "GTS.esp|64319D"
DarkArts_Aug3 = "GTS.esp|19D462"
DarkArts_Max = "GTS.esp|63E09A"
DestructionBasics = "GTS.esp|587C4A"
DevastatingSprint = "GTS.esp|123BEB"
DisastrousTremor = "GTS.esp|61FA97"
EnhancedCapacity = "GTS.esp|462228"
EternalCalamity = "GTS.esp|5ED064"
ExtraGrowth = "GTS.esp|332563"
ExtraGrowthMax = "GTS.esp|397972"
FastShrink = "GTS.esp|16081F"
Gluttony = "GTS.esp|33C764"
GrowingPressure = "GTS.esp|1E93A9"
GrowthDesirePerk = "GTS.esp|128CF6"
GrowthDesirePerkAug = "GTS.esp|829231"
GrowthOfStrength = "GTS.esp|151519"
GrowthOnHitPerk = "GTS.esp|30EE52"
HealthGate = "GTS.esp|4E0B39"
HealthRegenPerk = "GTS.esp|18E160"
hhBonus = "GTS.esp|271EF1"
HugCrush = "GTS.esp|60656E"
HugCrush_Greed = "GTS.esp|606571"
HugCrush_HugsOfDeath = "GTS.esp|629C98"
HugCrush_LovingEmbrace = "GTS.esp|7598CE"
HugCrush_MightyCuddles = "GTS.esp|60656F"
HugCrush_ToughGrip = "GTS.esp|606570"
KillerThighs = "GTS.esp|587C4B"
LaunchDamage = "GTS.esp|2496E9"
LethalShrink = "GTS.esp|160820"
LifeAbsorption = "GTS.esp|87F341"
LifeSteal = "GTS.esp|2496E8"
MightOfDragons = "GTS.esp|67FDAC"
MightOfGiants = "GTS.esp|6AD6B1"
MightyLegs = "GTS.esp|123BE9"
NoSpeedLoss = "GTS.esp|2E663B"
OnTheEdge = "GTS.esp|4399E3"
QuickApproach = "GTS.esp|123BEA"
RandomGrowth = "GTS.esp|35AD69"
RandomGrowthAug = "GTS.esp|865E3E"
RandomGrowthTerror = "GTS.esp|865E3F"
RavagingInjuries = "GTS.esp|128CF5"
RealCruelty = "GTS.esp|142205"
RumblingFeet = "GTS.esp|1CAD91"
ShrinkingGaze = "GTS.esp|889543"
SizeConversion = "GTS.esp|610774"
SizeReserve = "GTS.esp|4204CE"
SizeReserveAug = "GTS.esp|4C7638"
SizeReserveAug2 = "GTS.esp|4255D0"
SkilledGTS = "GTS.esp|61A996"
SoulVorePerk = "GTS.esp|33C765"
StaggerImmunity = "GTS.esp|0AA3B2"
TrueGiantess = "GTS.esp|128CF4"
VorePerk = "GTS.esp|355C68"
WrathfulCalamity = "GTS.esp|856B3C"
SizeManipulation = "GTS.esp|128CF2"
ExpandedGrowth = "GTS.esp|128CF3"
TalkToActor = "GTS.esp|5F7265" #Used In Papyrus

[EXPL] # Explosions ------------------------------------------------------------------------------------------------------------------------------------

#---------- GTS
BloodExplosion = "GTS.esp|01CE9D"
BloodFX = "Dawnguard.esm|00E7B4"
footstepExplosion = "GTS.esp|035C81"
draugrexplosion = "GTS.esp|035C80"

[GLOB] # Globals ------------------------------------------------------------------------------------------------------------------------------------

#---------- GTS Perk Tree
OpenGTSSkillMenu = "GTS.esp|1421FF"
GtsSkillLevel = "GTS.esp|142200"
GtsSkillRatio = "GTS.esp|142202"
GtsSkillProgress = "GTS.esp|142201"
GtsSkillPerkPoints = "GTS.esp|2352E1" 

#---------- Survival Mode
# Survival Values
Survival_HungerNeedMaxValue = "ccQDRSSE001-SurvivalMode.esl|00080C"
Survival_HungerNeedValue = "ccQDRSSE001-SurvivalMode.esl|00081A"

# Survival stages
Survival_HungerStage1Value = "ccQDRSSE001-SurvivalMode.esl|000806"
Survival_HungerStage2Value = "ccQDRSSE001-SurvivalMode.esl|000802"
Survival_HungerStage3Value = "ccQDRSSE001-SurvivalMode.esl|000803"
Survival_HungerStage4Value = "ccQDRSSE001-SurvivalMode.esl|000804"
Survival_HungerStage5Value = "ccQDRSSE001-SurvivalMode.esl|000805"

# Toggle
Survival_ModeEnabled = "ccQDRSSE001-SurvivalMode.esl|000826"

[QUST] # Quests ------------------------------------------------------------------------------------------------------------------------------------

#---------- GTS
MainQuest = "GTS.esp|005E3A"
ManagerQuest = "GTS.esp|000D62"


[FACT] # Factions ------------------------------------------------------------------------------------------------------------------------------------

#---------- Base Game
FollowerFaction = "Skyrim.esm|05C84E"
DwarwenAutomatonFaction = "Skyrim.esm|043598"
DraugrFaction = "Skyrim.esm|02430D"

#---------- Sexlab
SexLabAnimatingFaction = "SexLab.esm|00E50F"

[IDPS] # Impacts ------------------------------------------------------------------------------------------------------------------------------------

#---------- GTS
GtsBloodSprayImpactSet = "GTS.esp|01CEA7"
GtsBloodSprayImpactSetVore = "GTS.esp|024578"
GtsBloodSprayImpactSetVoreMedium = "GTS.esp|024579"
GtsBloodSprayImpactSetVoreSmallest = "GTS.esp|02457A"

[RACE] # Races ------------------------------------------------------------------------------------------------------------------------------------

#---------- Base Game
dragonRace = "Skyrim.esm|012E82"
FrostbiteSpiderRace = "Skyrim.esm|0131F8"
FrostbiteSpiderRaceGiant = "Skyrim.esm|04E507"
FrostbiteSpiderRaceLarge = "Skyrim.esm|053477"
ChaurusReaperRace = "Skyrim.esm|0A5601"
ChaurusRace = "Skyrim.esm|0131EB"
DLC1ChaurusHunterRace = "Dawnguard.esm|0051FB"
DLC1_BF_ChaurusRace = "Dawnguard.esm|015136"
DLC2ExpSpiderBaseRace = "Dragonborn.esm|014449"
DLC2ExpSpiderPackmuleRace = "Dragonborn.esm|027483"
DLC2AshHopperRace = "Dragonborn.esm|01B658"
IcewraithRace = "Skyrim.esm|0131FE"
MammothRace = "Skyrim.esm|0131FF"
GiantRace = "Skyrim.esm|0131F9"

[KYWD] # Keywords ------------------------------------------------------------------------------------------------------------------------------------

#---------- GTS
BlackListKeyword = "GTS.esp|6A85AF"
CountAsFollower = "GTS.esp|88E644"

#---------- Base Game
UndeadKeyword = "Skyrim.esm|013796"
DwemerKeyword = "Skyrim.esm|01397A"
DragonKeyword = "Skyrim.esm|035D59"
VampireKeyword = "Skyrim.esm|0A82BB"
AnimalKeyword = "Skyrim.esm|013798"
CreatureKeyword = "Skyrim.esm|013795"
DarkSouls = "Skyrim.esm|0C1E8F"
SummonUndead = "Skyrim.esm|02482B"
ActorTypeNPC = "Skyrim.esm|013794"

[CONT] # Container ------------------------------------------------------------------------------------------------------------------------------------

#---------- GTS
Dropbox = "GTS.esp|6AD6B0"
Dropbox_Undead = "GTS.esp|6BC9BC"
Dropbox_Mechanical = "GTS.esp|6C1ABE"
Dropbox_Soul = "GTS.esp|6C1ABD"
Dropbox_Bug = "GTS.esp|6C1ABF"

[LVLI] # Leveled List Item ------------------------------------------------------------------------------------------------------------------------------------

#---------- GTS
LootList_Master = "GTS.esp|7C3DFB"
